
name: CI

on:
  push:

  pull_request:

  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-node@v1

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/checkout@v2

    - name: test
      run: |
        go install github.com/ysmood/golangci-lint@latest && golangci-lint
        go generate
        go test
